=== AndersonOlivos/DAW-SAFA/1DAW/LENGUAJE_DE_MARCAS/UT5/TareaXSLT/Ejercicio1/pokedex.dtd
<!ELEMENT pokedex (pokemon*)>

<!-- POKEMON -->

<!ELEMENT pokemon (evoluciones, tipologia, datos_generales, stats_base)>
<!ATTLIST pokemon nombre CDATA #REQUIRED>
<!ATTLIST pokemon num_pokedex CDATA #REQUIRED>
<!ATTLIST pokemon url_imagen CDATA #REQUIRED>

<!-- DATOS GENERALES -->

<!ELEMENT datos_generales (altura, peso, sexo, categoria, habilidad*)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT habilidad (#PCDATA)>

<!-- TIPOLOGIA -->

<!ELEMENT tipologia (tipos, debilidades, fortalezas)>
<!ELEMENT tipos (tipo)>
<!ELEMENT tipo (descripcion)>
<!ELEMENT descripcion (#PCDATA)>

<!ELEMENT debilidades (debilidad)>
<!ELEMENT debilidad (tipo_debilidad, efectividad)>
<!ELEMENT tipo_debilidad (#PCDATA)>
<!ELEMENT efectividad (#PCDATA)>

<!ELEMENT fortalezas (fortaleza*)>
<!ELEMENT fortaleza (tipo_fortaleza, efectividad_fortaleza)>
<!ELEMENT tipo_fortaleza (#PCDATA)>
<!ELEMENT efectividad_fortaleza (#PCDATA)>

<!-- STATS BASE -->

<!ELEMENT stats_base (ps, at, def, spat, spde, vel)>
<!ELEMENT ps (#PCDATA)>
<!ELEMENT at (#PCDATA)>
<!ELEMENT def (#PCDATA)>
<!ELEMENT spat (#PCDATA)>
<!ELEMENT spde (#PCDATA)>
<!ELEMENT vel (#PCDATA)>

<!-- EVOLUCIONES -->

<!ELEMENT evoluciones (evolucion*)>
<!ELEMENT evolucion (orden, num_pokedex)>
<!ELEMENT orden (#PCDATA)>
<!ELEMENT num_pokedex (#PCDATA)>

=== AndersonOlivos/DAW-SAFA/1° DAW/LENGUAJE DE MARCAS/UT5/TareaXSLT/Ejercicio1/pokedex.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pokedex SYSTEM "pokedex.dtd">
<?xml-model href="pokedex.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<?xml-stylesheet href="pokemon.xslt" type="text/xsl"?>
<pokedex>
    <pokemon nombre="bulbasaur" num_pokedex="1" url_imagen="https://images.wikidexcdn.net/mwuploads/wikidex/thumb/4/43/latest/20190406170624/Bulbasaur.png/800px-Bulbasaur.png">
        <evoluciones>
            <evolucion>
                <orden>-1</orden>
                <num_pokedex>2</num_pokedex>
            </evolucion>
        </evoluciones>
        <tipologia>
            <tipos>
                <tipo>
                    <descripcion>planta</descripcion>
                </tipo>
            </tipos>
            <debilidades>
                <debilidad>
                    <tipo_debilidad>fuego</tipo_debilidad>
                    <efectividad>x2</efectividad>
                </debilidad>
            </debilidades>
            <fortalezas>
                <fortaleza>
                    <tipo_fortaleza>agua</tipo_fortaleza>
                    <efectividad_fortaleza>x2</efectividad_fortaleza>
                </fortaleza>
                <fortaleza>
                    <tipo_fortaleza>tierra</tipo_fortaleza>
                    <efectividad_fortaleza>x2</efectividad_fortaleza>
                </fortaleza>
            </fortalezas>
        </tipologia>
        <datos_generales>
            <altura>0.45</altura>
            <peso>20</peso>
            <sexo>M</sexo>
            <categoria>Semilla</categoria>
            <habilidad>Espesura</habilidad>
        </datos_generales>
        <stats_base>
            <ps>30</ps>
            <at>10</at>
            <def>12</def>
            <spat>15</spat>
            <spde>13</spde>
            <vel>5</vel>
        </stats_base>
        
    </pokemon>
    <pokemon nombre="pikachu" num_pokedex="1" url_imagen="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw3iIiDJQW4HYJk2osK19O3RQ4Hs4MDSF8PQ&s">
        <evoluciones>
            <evolucion>
                <orden>-1</orden>
                <num_pokedex>2</num_pokedex>
            </evolucion>
        </evoluciones>
        <tipologia>
            <tipos>
                <tipo>
                    <descripcion>planta</descripcion>
                </tipo>
            </tipos>
            <debilidades>
                <debilidad>
                    <tipo_debilidad>fuego</tipo_debilidad>
                    <efectividad>x2</efectividad>
                </debilidad>
            </debilidades>
            <fortalezas>
                <fortaleza>
                    <tipo_fortaleza>agua</tipo_fortaleza>
                    <efectividad_fortaleza>x2</efectividad_fortaleza>
                </fortaleza>
                <fortaleza>
                    <tipo_fortaleza>tierra</tipo_fortaleza>
                    <efectividad_fortaleza>x2</efectividad_fortaleza>
                </fortaleza>
            </fortalezas>
        </tipologia>
        <datos_generales>
            <altura>0.45</altura>
            <peso>20</peso>
            <sexo>M</sexo>
            <categoria>Semilla</categoria>
            <habilidad>Espesura</habilidad>
        </datos_generales>
        <stats_base>
            <ps>30</ps>
            <at>10</at>
            <def>12</def>
            <spat>15</spat>
            <spde>13</spde>
            <vel>5</vel>
        </stats_base>
        
    </pokemon>
</pokedex>
